#------------------------------------------------------------------------------
# Sends an email from the neonFORGE Office 365 account associated with the
# currently signed-in 1Passwork user.

name: neon-send-mail
description: Sends an email via Office 365
inputs:
  to: 
    description: Target email addresses separated by commas.
    required: true
  subject: 
    description: The subject line
    required: true
  cc:
    description: Optional CC email addresses separated by commas.
    required: false
  bcc:
    description: Optional BCC address separated by commas.
    required: false
  body:
    description: Optional email body text.
    required: false
    default: ""
  bodyAsHtml: 
    description: Optionally indicates that the body text is HTML.
    required: false
    default: false
  runs:
    using: composite
    steps:
    - shell: pwsh
      run: |
        
