#------------------------------------------------------------------------------
# Sends an email from the neonFORGE Office 365 account associated with the
# currently signed-in 1Password user.

name: neon-send-mail
description: Sends an email via Office 365
inputs:
  to: 
    description: Target email addresses separated by commas.
    required: true
  subject: 
    description: The subject line
    required: true
  cc:
    description: Optional CC email addresses separated by commas.
    required: false
  bcc:
    description: Optional BCC address separated by commas.
    required: false
  body:
    description: Optional email body text.
    required: false
    default: ""
  bodyAsHtml: 
    description: Optionally indicates that the body text is HTML.
    required: false
    default: false
  runs:
    using: composite
    steps:
    - shell: pwsh
      run: |
        
        # $debug(jefflill): TEST CODE
        #
        # $env:to      = "jeff@neonforge.com"
        # $env:subject = "HELLO WORLD!"
        # $env:body    = "Is this thing working?"
        
        return  # Email is not currently working
      
        # Pick up the deployment related functions
        
        . $env:NC_ROOT/Powershell/deployment.ps1
      
        # Fetch the credentials

        if ($env:DEVBOT_MASTER_PASSWORD -eq $null)
        {
            # $todo(jefflill): Error out here
        }

        $username    = GetSecretValue "NEONFORGE_LOGIN[username]" 
        $password    = GetSecretValue "NEONFORGE_LOGIN[password]"
        $credentials = New-Object -TypeName System.Net.NetworkCredential -ArgumentList $username, $password
     
        # Construct the email message

        $message = New-Object System.Net.Mail.MailMessage
        
        ForEach ($address in $env:to.Split(",", [System.StringSplitOptions]::RemoveEmptyEntries))
        {
            $address = $address.Trim()
            if ($address -ne "")
            {
                $address = New-Object -TypeName System.Net.Mail.MailAddress -ArgumentList $address
                $message.To.Add($address)
            }
        }
        
        $message.From       = New-Object -TypeName System.Net.Mail.MailAddress -ArgumentList $username
        $message.Subject    = $env:subject
        $message.Body       = $env:body
        $message.IsBodyHtml = $env:bodyAsHtml

        # Send the message
        
        $smtp             = New-Object Net.Mail.SmtpClient("smtp.office365.com", 587)
        $smtp.Credentials = $credentials
        $smtp.EnableSsl   = $true
        $smtp.Send($message)

  
