#------------------------------------------------------------------------------
# Sends an email from the neonFORGE Office 365 account associated with the
# currently signed-in 1Passwork user.

name: neon-send-mail
description: Sends an email via Office 365
inputs:
  to: 
    description: Target email addresses separated by commas.
    required: true
  subject: 
    description: The subject line
    required: true
  cc:
    description: Optional CC email addresses separated by commas.
    required: false
  bcc:
    description: Optional BCC address separated by commas.
    required: false
  body:
    description: Optional email body text.
    required: false
    default: ""
  bodyAsHtml: 
    description: Optionally indicates that the body text is HTML.
    required: false
    default: false
  runs:
    using: composite
    steps:
    - shell: pwsh
      run: |
        # Pick up the deployment related functions
        . ./$env:NC_ROOT/Powershell/deployment.ps1
        
        $username    = GetSecretPassword "NEONFORGE_LOGIN[username]"
        $password    = GetSecretPassword "NEONFORGE_LOGIN[password]"
        $credentials = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $username, $password
        
        $message            = New-Object System.Net.Mail.MailMessage
        $message.From       = $username
        $message.To         = $env:to.Split([System.StringSplitOptions]::RemoveEmptyEntries])
        $message.Subject    = $env:subject
        $message.Body       = $env:body
        $message.IsBodyHtml = $env:bodyAsHtml
        
        $smtp             = New-Object Net.Mail.SmtpClient(smtp.office365.com, 587)
        $smtp.Credentials = $credentials
        $smtp.Send($message)
        
        
        
