#------------------------------------------------------------------------------
# Sends an email from the neonFORGE Office 365 account associated with the
# currently signed-in 1Passwork user.

name: neon-send-mail
description: Sends an email via Office 365
inputs:
  to: 
    description: Target email addresses separated by commas.
    required: true
  subject: 
    description: The subject line
    required: true
  cc:
    description: Optional CC email addresses separated by commas.
    required: false
  bcc:
    description: Optional BCC address separated by commas.
    required: false
  body:
    description: Optional email body text.
    required: false
    default: ""
  bodyAsHtml: 
    description: Optionally indicates that the body text is HTML.
    required: false
    default: false
  runs:
    using: composite
    steps:
    - shell: pwsh
      run: |
    # Pick up the deployment related functions
        
    . $env:NC_ROOT/Powershell/deployment.ps1

    function Send
    {        
        # Fetch the credentials

        if ($env:1Password -eq $null)
        {
        }
        
        $username    = GetSecretPassword "NEONFORGE_LOGIN[username]" 
        $password    = GetSecretPassword "NEONFORGE_LOGIN[password]"
        $credentials = New-Object -TypeName System.Net.NetworkCredential -ArgumentList $username, $password
        
        # Construct the email message

        $toList = New-Object -TypeName MailAddressCollection 
        
        ForEach ($address in $env:to.Split([System.StringSplitOptions]::RemoveEmptyEntries))
        {
            $address = $address.Trim()
            if ($address -ne "")
            {
                $address = New-Object -TypeName System.Net.Mail.MailAddress -ArgumentList $address
                $toList.Add($address)
            }
        }
        
        $message            = New-Object System.Net.Mail.MailMessage
        $message.From       = New-Object -TypeName System.Net.Mail.MailAddress -ArgumentList $username
        $message.To         = $toList 
        $message.Subject    = $env:subject
        $message.Body       = $env:body
        $message.IsBodyHtml = $env:bodyAsHtml
        
        # Send the message
        
        $smtp             = New-Object Net.Mail.SmtpClient("smtp.office365.com", 587)
        $smtp.Credentials = $credentials
        $smtp.EnableSsl   = $true

        $smtp.Send($message)
    }

    $env:to      = "jeff@neonforge.com"
    $env:subject = "HELLO WORLD!"
    $env:body    = "Is this thing working?"

    Send
